=head1 Linux::Iwd

This class provides known networks and adapters information.

 use Linux::Iwd;
 
 my $iwd = Linux::Iwd->new();

=head1 Attributes

=head2 C<has 'Adapters'; #34>

List of (available, active) adapters Linux::Iwd::Adapter. The list is
accessible via native Moose array traits with lower case attribute
suffix (e.g. C<all_adapters>).

=head2 C<has 'KnownNetworks'; #56>

List of known (configured) networks Linux::Iwd::KnownNetwork The list
is accessible via native Moose array traits with lower case attribute
suffix (e.g. C<all_known_attributes>).

=cut

#Pod::HTML2Pod conversion notes:
# 726 bytes of input
#Mon Jan 16 21:04:56 2023 tschaefer
# No a_name switch not specified, so will not try to render <a name='...'>
# Will try to render <a href='...'>
# Untranslatable link: "Iwd/Adapter.html"
# Untranslatable link: "Iwd/KnownNetwork.html"
